### ISSUE TITLE
Package URL in README is old

### ISSUE THREAD

**Issue by shunkosa** [muenzpraeger/salesforce-einstein-vision-apex#14]
Hi @muenzpraeger ,
The package URL in README.md seems to be old. The latest package url is the following.
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t0Y000000smT0
Would you please update the link?

**Comment by muenzpraeger** [comment]
This repo got deprecated over a year ago. Check out the README headline which points to the successor => https://github.com/muenzpraeger/salesforce-einstein-platform-apex
